"""
Adds the group "Records against measured data (NIST ThermoML Archive)" to validation/report/cases.json and writes
its references, validation/report/reference/measured.json (proposal 0008, Part B). The rest of cases.json is
kept as it is.

    python validation/report/make_measured_cases.py

For each component with measured values in validation/data/pure/measured/thermoml_<id>.json (from
validation/python/check_measured.py), except those whose records are fitted to these values themselves
(validation/python/measured_components.py), and for each property with a tolerance in proposal 0002, one
result: the median over the articles of each article's median deviation of the record from the measured
values, in percent (the rules of check_measured.py and test/measured-checks.test.js; computed by
scripts/engineering-report.mjs). Its reference is zero deviation; its tolerance that of proposal 0002.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "validation/python"))
from check_measured import KNOWN  # noqa: E402  (known issues: records out of tolerance that stay for now)
CASES = ROOT / "validation/report/cases.json"
REF = ROOT / "validation/report/reference/measured.json"
comp = json.loads((ROOT / "src/data/components.json").read_text())["components"]

TOL = {
    "measured1": {"abs": 1.0, "unit": "%", "basis": "Proposal 0002 (vapour pressure, liquid density: 1 %), as the median deviation of the articles"},
    "measured2": {"abs": 2.0, "unit": "%", "basis": "Proposal 0002 (heat capacity, heat of vaporization: 2 %), as the median deviation of the articles"},
    "measured5": {"abs": 5.0, "unit": "%", "basis": "Proposal 0002 (viscosity, thermal conductivity: 5 %), as the median deviation of the articles"},
}
PROPS = {"vapourPressure": "measured1", "liquidDensity": "measured1", "liquidHeatCapacity": "measured2",
         "heatOfVaporization": "measured2", "liquidViscosity": "measured5", "liquidThermalConductivity": "measured5"}


def j(v):
    return json.dumps(v, ensure_ascii=False)


def write_cases(out):
    """The layout of make_cases.py: one tolerance, one case and one curve per line."""
    L = ["{", f' "_about": {j(out["_about"])},', f' "version": {j(out["version"])},', ' "tolerances": {']
    L += [",\n".join(f"  {j(k)}: {j(v)}" for k, v in out["tolerances"].items())]
    L += [" },", ' "groups": [']
    gs = []
    for g in out["groups"]:
        gs.append(f'  {{"id": {j(g["id"])}, "title": {j(g["title"])}, "cases": [\n'
                  + ",\n".join("   " + j(c) for c in g["cases"]) + "\n  ]}")
    L += [",\n".join(gs), " ],", ' "curves": [', ",\n".join("  " + j(c) for c in out["curves"]), " ]", "}"]
    txt = "\n".join(L) + "\n"
    assert json.loads(txt) == json.loads(json.dumps(out))
    CASES.write_text(txt)


def main():
    out = json.loads(CASES.read_text())
    ids = sorted(f.stem[len("thermoml_"):] for f in (ROOT / "validation/data/pure/measured").glob("thermoml_*.json"))
    ids = [c for c in ids if c in comp and "Measured data only" not in comp[c].get("constants_source", "")]
    cases = [{"id": f"measured/{c}/{prop}", "type": "measuredSet", "component": c, "name": comp[c]["name"], "property": prop,
              "data": f"validation/data/pure/measured/thermoml_{c}.json",
              "quantities": [{"key": "medianDev_pct", "tol": tol}],
              **({"known": KNOWN[(c, prop)]} if (c, prop) in KNOWN else {})} for c in ids for prop, tol in PROPS.items()]
    group = {"id": "measured", "title": "Records against measured data (NIST ThermoML Archive)", "cases": cases}
    out["groups"] = [g for g in out["groups"] if g["id"] != "measured"] + [group]
    out["tolerances"].update(TOL)
    write_cases(out)
    values = {c["id"]: {"medianDev_pct": {"value": 0.0, "source": "thermoml-measured",
                                          "detail": "zero deviation from the measured values in %s" % c["data"]}} for c in cases}
    REF.write_text(json.dumps({
        "_about": "Reference values for the 'Records against measured data' group of validation/report/cases.json: the "
                  "result is a deviation from measured values, so its reference is zero. Generated by "
                  "validation/report/make_measured_cases.py; do not edit by hand.",
        "sources": {"thermoml-measured": {
            "citation": "NIST TRC ThermoML Archive: the pure-component values of each component, stored with their "
                        "articles in validation/data/pure/measured/thermoml_<id>.json (validation/python/check_measured.py)",
            "url": "https://trc.nist.gov/ThermoML/", "access": "Open data (NIST)"}},
        "values": values}, indent=1, ensure_ascii=False) + "\n")
    print("%d components, %d results" % (len(ids), len(cases)))


if __name__ == "__main__":
    main()
