// Writes docs/DATA_WANTED.md: which binary pairs among the current components still
// have no parameters, and which have only databank values that would benefit from a
// fit to open experimental data. Run after changing src/data: `npm run wanted`.
import { readFileSync, writeFileSync } from "node:fs";

const comps = JSON.parse(readFileSync(new URL("../src/data/components.json", import.meta.url))).components;
const pairs = JSON.parse(readFileSync(new URL("../src/data/binaries.json", import.meta.url))).pairs;
// Activity-model (NRTL/UNIQUAC) pairs only: light gases are described by equations of state.
const ids = Object.keys(comps).filter(id => comps[id].uniquac);
const name = id => comps[id].name;

const have = new Map();
for (const p of pairs) {
  const key = [p.i, p.j].sort().join("|");
  if (!have.has(key)) have.set(key, {});
  have.get(key)[p.model] = p.tier || "databank";
}

const missing = [], databankOnly = [], fitted = [];
for (let a = 0; a < ids.length; a++) for (let b = a + 1; b < ids.length; b++) {
  const key = [ids[a], ids[b]].sort().join("|");
  const label = `${name(ids[a])} + ${name(ids[b])}`;
  const h = have.get(key);
  if (!h) missing.push(label);
  else if (Object.values(h).includes("fitted")) fitted.push(label);
  else databankOnly.push(`${label} (${Object.keys(h).join(", ")})`);
}

const total = ids.length * (ids.length - 1) / 2;
const md = `# Data wanted

Generated by \`npm run wanted\` from \`src/data/\`. Do not edit by hand.

${ids.length} components make ${total} pairs: ${fitted.length} fitted to experimental data,
${databankOnly.length} from a databank only, ${missing.length} with no parameters yet.

**How to help:** pick a pair, look for open-access VLE data (see
[CONTRIBUTING.md](../CONTRIBUTING.md#2-find-open-data-for-a-component-or-pair)), and open a
[validation case](https://github.com/FaireDose/Fugacity/issues/new?template=validation-case.yml)
issue with the source. Mention the pair in the issue title so others can see it is taken.
Some pairs are only partly miscible (for example water with benzene, toluene or
chloroform); liquid-liquid data for them is welcome too.

## No parameters yet (${missing.length})

${missing.map(m => `- ${m}`).join("\n") || "- none"}

## Databank only, would benefit from a fit to open data (${databankOnly.length})

${databankOnly.map(m => `- ${m}`).join("\n") || "- none"}

## Fitted to experimental data (${fitted.length})

${fitted.map(m => `- ${m}`).join("\n") || "- none"}
`;
writeFileSync(new URL("../docs/DATA_WANTED.md", import.meta.url), md);
console.log(`docs/DATA_WANTED.md: ${missing.length} missing, ${databankOnly.length} databank only, ${fitted.length} fitted`);
