"""Build src/data/kij.json from the ChemSep interaction-parameter files pr.ipd and srk.ipd.

Source files (ChemSep, Copyright Harry Kooijman and Ross Taylor, Artistic License 2.0),
as redistributed with DWSIM:
  https://github.com/DanWBR/dwsim/blob/windows/DWSIM.Thermodynamics/Assets/ChemSepIPD/pr.ipd
  https://github.com/DanWBR/dwsim/blob/windows/DWSIM.Thermodynamics/Assets/ChemSepIPD/srk.ipd

Both files list several DECHEMA data sets for some pairs (one line per data set, with the
DECHEMA page and the temperature range). Fugacity keeps one entry per pair: the one kept in
the copy of pr.ipd distributed with the open-source thermo library (thermo 0.6.1,
thermo/Interaction Parameters/ChemSep/pr.ipd, which lists one data set per pair), and for
SRK the line from the same DECHEMA page. The other entries are recorded in `alternatives`.
The temperature range of the chosen data set, when the file states one, is stored as
`source.T_range_K`; the engine warns outside it.

Databank values contradicted by open data are then replaced by fitted values: run
validation/python/eos_fit_kij.py --write after this script.

Usage:
  python validation/python/eos_kij_from_chemsep.py DWSIM_pr.ipd DWSIM_srk.ipd [--write]
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
THERMO_PR = None
try:
    import thermo
    THERMO_PR = os.path.join(os.path.dirname(thermo.__file__), "Interaction Parameters", "ChemSep", "pr.ipd")
except ImportError:
    pass


def t_range(comment):
    """Temperature range [Tmin, Tmax] in K stated in a ChemSep comment ("T=90-113K", "T=250K")."""
    m = re.search(r"T=([\d.]+)(?:-([\d.]+))?", comment)
    if not m:
        return None
    lo = float(m.group(1))
    hi = float(m.group(2)) if m.group(2) else lo
    return [lo, hi]


def parse(path, cas):
    """Lines 'CAS1 CAS2 k12 comments' where both CAS numbers are Fugacity components."""
    out = []
    for line in open(path, encoding="latin-1"):
        p = line.split()
        if len(p) >= 3 and p[0] in cas and p[1] in cas:
            comment = line.split(p[2], 1)[1].strip()
            page = [w for w in comment.split() if w.startswith("p") and w[1:].isdigit()]
            out.append({"i": cas[p[0]], "j": cas[p[1]], "printed": p[2], "kij": float(p[2]),
                        "comment": comment, "page": page[-1] if page else None, "line": line.rstrip()})
    return out


def main():
    pr_path, srk_path = sys.argv[1], sys.argv[2]
    comps = json.load(open(os.path.join(ROOT, "src", "data", "components.json")))["components"]
    cas = {c["cas"]: k for k, c in comps.items()}
    pr, srk = parse(pr_path, cas), parse(srk_path, cas)
    kept = {(e["i"], e["j"]): e["page"] for e in parse(THERMO_PR, cas)}
    print(f"pr.ipd: {len(pr)} lines, srk.ipd: {len(srk)} lines among the 16 components")
    pairs = []
    for model, rows, fname in (("PR", pr, "pr.ipd"), ("SRK", srk, "srk.ipd")):
        keys = []
        for r in rows:
            if (r["i"], r["j"]) not in keys:
                keys.append((r["i"], r["j"]))
        for key in keys:
            entries = [r for r in rows if (r["i"], r["j"]) == key]
            page = kept[key]
            chosen = [r for r in entries if r["page"] == page]
            assert len(chosen) == 1, (model, key, page)
            c = chosen[0]
            pairs.append({
                "model": model, "i": key[0], "j": key[1], "kij": c["kij"], "tier": "databank",
                "source": {
                    "file": f"ChemSep {fname}",
                    "printed": c["printed"],
                    "conditions": c["comment"],
                    "entries_in_file": len(entries),
                    **({"T_range_K": t_range(c["comment"])} if t_range(c["comment"]) else {}),
                },
                "alternatives": [f"{r['printed']} ({r['comment']})" for r in entries if r is not c],
            })
    n_pr = sum(p["model"] == "PR" for p in pairs)
    n_srk = sum(p["model"] == "SRK" for p in pairs)
    print(f"pairs: PR {n_pr}, SRK {n_srk}")
    for p in pairs:
        print(f"{p['model']:4s} {p['i']:10s} {p['j']:12s} {p['kij']:8.4f}  {p['source']['conditions']}  ({p['source']['entries_in_file']} entries)")
    doc = {
        "_about": "Binary interaction parameters k_ij (symmetric, k_ji = k_ij) for the Peng-Robinson and SRK equations of state with van der Waals one-fluid mixing rules. Pairs not listed use k_ij = 0, and the system reports them as such. Generated by validation/python/eos_kij_from_chemsep.py.",
        "source": {
            "name": "ChemSep interaction parameter files pr.ipd and srk.ipd (DECHEMA Peng-Robinson / Soave-Redlich-Kwong EOS data; library created by A. L. Dill 1996 and J. A. Clark 2014, updated by H. Kooijman)",
            "copy_used": "https://github.com/DanWBR/dwsim/tree/windows/DWSIM.Thermodynamics/Assets/ChemSepIPD",
            "license": "Artistic License 2.0, Copyright Harry Kooijman and Ross Taylor",
            "selection": "Where the file lists several DECHEMA data sets for a pair (entries_in_file > 1; the others are in `alternatives`), Fugacity uses the entry kept in the ChemSep pr.ipd copy distributed with the thermo library 0.6.1, and for SRK the entry from the same DECHEMA page. `printed` is the value as printed in the file; `conditions` is the file's comment (DECHEMA page, temperature and pressure range of the data).",
        },
        "pairs": pairs,
    }
    if "--write" in sys.argv:
        out = os.path.join(ROOT, "src", "data", "kij.json")
        with open(out, "w") as f:
            json.dump(doc, f, indent=1, ensure_ascii=False)
            f.write("\n")
        print("wrote", out)


if __name__ == "__main__":
    main()
