"""Reference values from CoolProp 8.0.0 for checking Peng-Robinson and SRK (src/thermo/eos).

CoolProp's Helmholtz-energy equations of state are reference-quality fits to experimental
data (the source equation of each fluid is cited in CoolProp's documentation,
http://www.coolprop.org/fluid_properties/PurePseudoPure.html); its mixture model for the
pairs used here is GERG-2008 (Kunz & Wagner, J. Chem. Eng. Data 57 (2012) 3032) as
implemented in CoolProp's HEOS backend. These are not cubic equations, so the comparison
shows the known limits of PR and SRK, not implementation errors.

Writes validation/data/eos/coolprop_reference.json and prints the deviation tables quoted
in the pull request (PR/SRK values from reference_eos.py).

Usage: python validation/python/eos_coolprop_compare.py [--write]
"""
import json
import os
import sys

import CoolProp
import CoolProp.CoolProp as CP
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from reference_eos import COMPS, Cubic, R  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))

FLUIDS = {"oxygen": "Oxygen", "nitrogen": "Nitrogen", "hydrogen": "Hydrogen", "methane": "Methane",
          "ethane": "Ethane", "ethylene": "Ethylene", "water": "Water", "methanol": "Methanol",
          "ethanol": "Ethanol", "acetone": "Acetone", "benzene": "Benzene", "toluene": "Toluene"}
GASES = ["oxygen", "nitrogen", "hydrogen", "methane", "ethane", "ethylene"]
TRS = [0.6, 0.7, 0.8, 0.9]
PRESSURES_BAR = [1, 10, 50, 100]


def eos_psat(model, cid, T):
    """Saturation pressure (Pa) of a pure component from the cubic, by equal fugacities."""
    e = Cubic(model, [cid])
    from scipy.optimize import brentq
    Tc, Pc = COMPS[cid]["Tc_K"], COMPS[cid]["Pc_Pa"]

    def g(lnP):
        P = np.exp(lnP)
        zl, n = e.Z(T, P, [1.0], "liquid")
        if n < 3:
            return np.nan
        return e.lnphi(T, P, [1.0], "liquid")[0] - e.lnphi(T, P, [1.0], "vapour")[0]
    # scan for a bracket among pressures with three roots
    grid = np.linspace(np.log(Pc) - 25, np.log(Pc), 2000)
    vals = [(u, g(u)) for u in grid]
    vals = [(u, v) for u, v in vals if np.isfinite(v)]
    for (u1, v1), (u2, v2) in zip(vals, vals[1:]):
        if v1 * v2 < 0:
            return float(np.exp(brentq(g, u1, u2, xtol=1e-14)))
    raise RuntimeError(f"no psat for {cid} at {T}")


def main():
    out = {"_about": "CoolProp %s reference values (pure-fluid reference equations of state; mixtures: GERG-2008 in CoolProp's HEOS backend). Generated by validation/python/eos_coolprop_compare.py." % CoolProp.__version__,
           "psat": [], "density": [], "mixture_bubble": []}
    print("Vapour pressure: PR and SRK vs CoolProp (%)")
    print(f"{'component':10s} {'Tr':>4s} {'T K':>8s} {'CoolProp kPa':>13s} {'PR %':>7s} {'SRK %':>7s}")
    for cid, fl in FLUIDS.items():
        for tr in TRS:
            T = round(tr * COMPS[cid]["Tc_K"], 2)
            if T < CP.PropsSI("Ttriple", fl) or T > CP.PropsSI("Tcrit", fl):
                continue
            p = CP.PropsSI("P", "T", T, "Q", 0, fl) / 1000
            pr = eos_psat("PR", cid, T) / 1000
            srk = eos_psat("SRK", cid, T) / 1000
            print(f"{cid:10s} {tr:4.1f} {T:8.2f} {p:13.4f} {100 * (pr / p - 1):7.2f} {100 * (srk / p - 1):7.2f}")
            out["psat"].append({"component": cid, "T_K": T, "P_kPa": p, "PR_kPa": pr, "SRK_kPa": srk})
    print("\nDensity at 300 K: PR vs CoolProp (%)")
    print(f"{'component':10s} {'P bar':>6s} {'phase':>8s} {'CoolProp kg/m3':>15s} {'PR %':>7s} {'SRK %':>7s} {'ideal gas %':>11s}")
    for cid in GASES:
        fl = FLUIDS[cid]
        for pb in PRESSURES_BAR:
            T, P = 300.0, pb * 1e5
            rho = CP.PropsSI("D", "T", T, "P", P, fl)
            ph = CP.PhaseSI("T", T, "P", P, fl)
            phase = "liquid" if "liquid" in ph else "vapour"
            MW = COMPS[cid]["MW"] / 1000
            vals = {}
            for model in ("PR", "SRK"):
                e = Cubic(model, [cid])
                Z, _ = e.Z(T, P, [1.0], phase)
                vals[model] = MW * P / (Z * R * T)
            ig = MW * P / (R * T)
            print(f"{cid:10s} {pb:6d} {ph:>8s} {rho:15.4f} {100 * (vals['PR'] / rho - 1):7.2f} {100 * (vals['SRK'] / rho - 1):7.2f} {100 * (ig / rho - 1):11.2f}")
            out["density"].append({"component": cid, "T_K": T, "P_kPa": P / 1000, "phase": phase, "coolprop_phase": ph,
                                   "rho_kg_m3": rho, "PR_kg_m3": vals["PR"], "SRK_kg_m3": vals["SRK"]})
    print("\nMixture bubble pressure: GERG-2008 (CoolProp HEOS) vs PR and SRK with ChemSep k_ij")
    for pair, T, xs in ((("methane", "ethane"), 200.0, [0.2, 0.4, 0.6, 0.8]), (("nitrogen", "methane"), 150.0, [0.1, 0.2, 0.3, 0.4])):
        AS = CP.AbstractState("HEOS", "&".join(FLUIDS[c] for c in pair))
        for x1 in xs:
            AS.set_mole_fractions([x1, 1 - x1])
            try:
                AS.update(CP.QT_INPUTS, 0, T)
            except Exception as ex:  # noqa: BLE001
                print("  CoolProp failed:", pair, T, x1, ex)
                continue
            p = AS.p() / 1000
            y1 = AS.mole_fractions_vapor()[0]
            print(f"  {pair[0]}+{pair[1]} T={T} x1={x1}: P={p:.2f} kPa y1={y1:.4f}")
            out["mixture_bubble"].append({"components": list(pair), "T_K": T, "x1": x1, "P_kPa": p, "y1": y1})
    if "--write" in sys.argv:
        path = os.path.join(ROOT, "validation", "data", "eos", "coolprop_reference.json")
        with open(path, "w") as f:
            json.dump(out, f, indent=1)
            f.write("\n")
        print("wrote", path)


if __name__ == "__main__":
    main()
