"""
Recalculates the concept-model Excel workbooks (src/ui/flowsheet-excel.js, { concept: true }) in LibreOffice and
compares every stream flow with CHEPTA: as exported (the workbook must reproduce CHEPTA's solution), and after
editing an input the way a person would (a feed flow, a drum's temperature or pressure), against CHEPTA run again
with the same change. The first comparison checks the formulas; the second measures the concept-design approximation
(constant activity coefficients and K-values at the drum's state). Writes docs/EXCEL_CONCEPT_CHECK.md.

Needs Node.js and LibreOffice (soffice). Usage: python validation/excel/check_concept.py
"""
import csv
import json
import re
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DOC = ROOT / "docs" / "EXCEL_CONCEPT_CHECK.md"
# LibreOffice recalculates every formula on load ("always"), not only the cached values
XCU = """<?xml version="1.0" encoding="UTF-8"?>
<oor:items xmlns:oor="http://openoffice.org/2001/registry" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<item oor:path="/org.openoffice.Office.Calc/Formula/Load"><prop oor:name="OOXMLRecalcMode" oor:op="fuse"><value>0</value></prop></item>
</oor:items>
"""


def edit(src, dst, sheet, cell, new):
    zin, zout = zipfile.ZipFile(src), zipfile.ZipFile(dst, "w", zipfile.ZIP_STORED)
    for it in zin.infolist():
        d = zin.read(it.filename)
        if it.filename == "xl/worksheets/sheet%d.xml" % sheet:
            t, n = re.subn(r'(<c r="%s" s="2"><v>)[^<]*(</v>)' % cell, r"\g<1>%r\2" % new, d.decode())
            assert n == 1, "input cell %s not found" % cell
            d = t.encode()
        zout.writestr(it, d)
    zout.close()


def recalc(xlsx, outdir, profile):
    subprocess.run(["soffice", "-env:UserInstallation=" + profile.as_uri(), "--headless", "--convert-to",
                    "csv:Text - txt - csv (StarCalc):44,34,76,1,,0,false,true,false,false,false,-1", "--outdir", str(outdir),
                    str(xlsx)], check=True, capture_output=True, timeout=300)
    rows = list(csv.reader(open(outdir / ("%s-Streams.csv" % xlsx.stem))))
    hdr = rows[0]
    flows = [r for r in rows if r and r[0].startswith("Flow ")]
    return {sid: [float(r[j]) for r in flows] for j, sid in enumerate(hdr) if j >= 2 and sid}


def compare(xl, ref):
    """Largest deviation relative to each stream's total flow, over every stream and component."""
    worst = 0.0
    for sid, f in ref.items():
        tot = sum(f)
        if tot > 1e-9 and sid in xl:
            worst = max(worst, max(abs(a - b) for a, b in zip(xl[sid], f)) / tot)
    return worst


def main():
    if not shutil.which("soffice"):
        raise SystemExit("LibreOffice (soffice) is needed")
    tmp = Path(tempfile.mkdtemp())
    (tmp / "profile" / "user").mkdir(parents=True)
    (tmp / "profile" / "user" / "registrymodifications.xcu").write_text(XCU)
    subprocess.run(["node", str(HERE / "make_cases.mjs"), str(tmp)], check=True)
    index = json.loads((tmp / "index.json").read_text())
    lines = ["# Excel concept model: recalculated in LibreOffice", "",
             "Generated by `validation/excel/check_concept.py`. Each workbook is the \"Excel concept model\" export of the "
             "flowsheet (`src/ui/flowsheet-excel.js`), recalculated by LibreOffice with every formula evaluated. "
             "\"As exported\" must reproduce CHEPTA's solution (it checks the formulas). After an edit, the workbook is "
             "compared with CHEPTA run again with the same change: that difference is the concept-design approximation "
             "(activity coefficients and, for a component without a vapour pressure at the drum temperature, K held at the "
             "exported state). Deviation: the largest difference of a component flow, relative to that stream's total flow.", "",
             "| Case | Change | Largest deviation from CHEPTA |", "|---|---|---|"]
    for f, c in index.items():
        xl = recalc(tmp / ("%s.xlsx" % f), tmp / f, tmp / "profile")
        d = compare(xl, c["reference"])
        lines.append("| %s | as exported | %.1e |" % (c["name"], d))
        print("%-55s %-32s %.1e" % (c["name"], "as exported", d))
        for k, e in enumerate(c["edits"]):
            g = "%s_edit%d" % (f, k + 1)
            edit(tmp / ("%s.xlsx" % f), tmp / ("%s.xlsx" % g), e["sheet"], e["cell"], e["new"])
            d = compare(recalc(tmp / ("%s.xlsx" % g), tmp / g, tmp / "profile"), e["reference"])
            lines.append("| | %s | %s |" % (e["label"], "%.1e" % d if d < 1e-6 else "%.1f %%" % (100 * d)))
            print("%-55s %-32s %.2e" % ("", e["label"], d))
    lines.append("")
    DOC.write_text("\n".join(lines))
    print("written", DOC.relative_to(ROOT))


if __name__ == "__main__":
    main()
